package storage

import (
	"database/sql"
	"errors"
	"log/slog"
	"myproject/internal/domain"
	"myproject/logger"
)

// ErrUserNotFound is returned when a user lookup fails.
var ErrUserNotFound = errors.New("user not found")

// CreateUser inserts a new user and returns the generated ID.
func (ds *DatabaseStorage) CreateUser(email, passwordHash string) (int, error) {
	ds.logger.Debug("Creating user",
		slog.String(logger.FieldOperation, "create_user"),
		slog.String(logger.FieldEmail, logger.MaskEmail(email)),
	)
	result, err := ds.db.Exec(
		"INSERT INTO users (email, password_hash, created_at) VALUES (?, ?, CURRENT_TIMESTAMP)",
		email, passwordHash,
	)
	if err != nil {
		ds.logger.Error("Failed to execute database insert",
			slog.String(logger.FieldOperation, "create_user"),
			slog.String(logger.FieldEmail, logger.MaskEmail(email)),
			slog.String("error", err.Error()),
		)
		return 0, mapSQLiteError(err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		ds.logger.Error("Failed to return id generated by database",
			slog.String(logger.FieldOperation, "create_user"),
			slog.String(logger.FieldEmail, logger.MaskEmail(email)),
			slog.String("error", err.Error()),
		)
		return 0, mapSQLiteError(err)
	}
	return int(id), nil
}

// GetUserByEmail retrieves a user by email, returns ErrUserNotFound if not exists.
func (ds *DatabaseStorage) GetUserByEmail(email string) (*domain.User, error) {
	ds.logger.Debug("Fetching user by email",
		slog.String(logger.FieldOperation, "get_user_by_email"),
		slog.String(logger.FieldEmail, logger.MaskEmail(email)),
	)
	var user domain.User
	err := ds.db.QueryRow(
		"SELECT id, email, password_hash FROM users WHERE email = ?",
		email,
	).Scan(&user.ID, &user.Email, &user.PasswordHash)

	if err != nil {
		if err == sql.ErrNoRows {
			return nil, ErrUserNotFound
		}
		ds.logger.Error("Failed to query database select from users",
			slog.String(logger.FieldOperation, "get_user_by_email"),
			slog.String(logger.FieldEmail, logger.MaskEmail(email)),
			slog.String("error", err.Error()),
		)
		return nil, mapSQLiteError(err)
	}

	return &user, nil
}

// GetUserByID retrieves a user by ID, returns ErrUserNotFound if not exists.
func (ds *DatabaseStorage) GetUserByID(id int) (*domain.User, error) {
	ds.logger.Debug("Fetching user by id",
		slog.String(logger.FieldOperation, "get_user_by_id"),
		slog.Int(logger.FieldUserID, id),
	)
	var user domain.User
	err := ds.db.QueryRow(
		"SELECT id, email, password_hash FROM users WHERE id = ?",
		id,
	).Scan(&user.ID, &user.Email, &user.PasswordHash)

	if err != nil {
		if err == sql.ErrNoRows {
			return nil, ErrUserNotFound
		}
		ds.logger.Error("Failed to query database select from users",
			slog.String(logger.FieldOperation, "get_user_by_id"),
			slog.Int(logger.FieldUserID, id),
			slog.String("error", err.Error()),
		)
		return nil, mapSQLiteError(err)
	}

	return &user, nil
}

// EmailExists checks if an email is already registered in the database.
func (ds *DatabaseStorage) EmailExists(email string) (exists bool, err error) {
	ds.logger.Debug("Checking email existence",
		slog.String(logger.FieldOperation, "email_exists"),
		slog.String(logger.FieldEmail, logger.MaskEmail(email)),
	)
	err = ds.db.QueryRow(
		"SELECT EXISTS (SELECT 1 FROM users WHERE email = ?)",
		email,
	).Scan(&exists)

	if err != nil {
		ds.logger.Error("Failed to query database select from users",
			slog.String(logger.FieldOperation, "email_exists"),
			slog.String(logger.FieldEmail, logger.MaskEmail(email)),
			slog.String("error", err.Error()),
		)
		return exists, mapSQLiteError(err)
	}

	return exists, nil
}
