// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: adapters/grpcserver/task_manager.proto

package grpcserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_adapters_grpcserver_task_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adapters_grpcserver_task_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_adapters_grpcserver_task_manager_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_adapters_grpcserver_task_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_adapters_grpcserver_task_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_adapters_grpcserver_task_manager_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_adapters_grpcserver_task_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adapters_grpcserver_task_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_adapters_grpcserver_task_manager_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_adapters_grpcserver_task_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_adapters_grpcserver_task_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_adapters_grpcserver_task_manager_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_adapters_grpcserver_task_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adapters_grpcserver_task_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_adapters_grpcserver_task_manager_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTaskRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateTaskReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskReply) Reset() {
	*x = CreateTaskReply{}
	mi := &file_adapters_grpcserver_task_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskReply) ProtoMessage() {}

func (x *CreateTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_adapters_grpcserver_task_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskReply.ProtoReflect.Descriptor instead.
func (*CreateTaskReply) Descriptor() ([]byte, []int) {
	return file_adapters_grpcserver_task_manager_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTaskReply) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type GetTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksRequest) Reset() {
	*x = GetTasksRequest{}
	mi := &file_adapters_grpcserver_task_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksRequest) ProtoMessage() {}

func (x *GetTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adapters_grpcserver_task_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksRequest.ProtoReflect.Descriptor instead.
func (*GetTasksRequest) Descriptor() ([]byte, []int) {
	return file_adapters_grpcserver_task_manager_proto_rawDescGZIP(), []int{6}
}

func (x *GetTasksRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetTasksReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*GetTasksReply_Task  `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksReply) Reset() {
	*x = GetTasksReply{}
	mi := &file_adapters_grpcserver_task_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksReply) ProtoMessage() {}

func (x *GetTasksReply) ProtoReflect() protoreflect.Message {
	mi := &file_adapters_grpcserver_task_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksReply.ProtoReflect.Descriptor instead.
func (*GetTasksReply) Descriptor() ([]byte, []int) {
	return file_adapters_grpcserver_task_manager_proto_rawDescGZIP(), []int{7}
}

func (x *GetTasksReply) GetTasks() []*GetTasksReply_Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type GetTasksReply_Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Done          bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksReply_Task) Reset() {
	*x = GetTasksReply_Task{}
	mi := &file_adapters_grpcserver_task_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksReply_Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksReply_Task) ProtoMessage() {}

func (x *GetTasksReply_Task) ProtoReflect() protoreflect.Message {
	mi := &file_adapters_grpcserver_task_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksReply_Task.ProtoReflect.Descriptor instead.
func (*GetTasksReply_Task) Descriptor() ([]byte, []int) {
	return file_adapters_grpcserver_task_manager_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetTasksReply_Task) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTasksReply_Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetTasksReply_Task) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_adapters_grpcserver_task_manager_proto protoreflect.FileDescriptor

const file_adapters_grpcserver_task_manager_proto_rawDesc = "" +
	"\n" +
	"&adapters/grpcserver/task_manager.proto\x12\n" +
	"grpcserver\"C\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rRegisterReply\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\"\n" +
	"\n" +
	"LoginReply\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"K\n" +
	"\x11CreateTaskRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"*\n" +
	"\x0fCreateTaskReply\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\"'\n" +
	"\x0fGetTasksRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x93\x01\n" +
	"\rGetTasksReply\x124\n" +
	"\x05tasks\x18\x01 \x03(\v2\x1e.grpcserver.GetTasksReply.TaskR\x05tasks\x1aL\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done2\xa2\x02\n" +
	"\vTaskManager\x12D\n" +
	"\bRegister\x12\x1b.grpcserver.RegisterRequest\x1a\x19.grpcserver.RegisterReply\"\x00\x12;\n" +
	"\x05Login\x12\x18.grpcserver.LoginRequest\x1a\x16.grpcserver.LoginReply\"\x00\x12J\n" +
	"\n" +
	"CreateTask\x12\x1d.grpcserver.CreateTaskRequest\x1a\x1b.grpcserver.CreateTaskReply\"\x00\x12D\n" +
	"\bGetTasks\x12\x1b.grpcserver.GetTasksRequest\x1a\x19.grpcserver.GetTasksReply\"\x00B\x1fZ\x1dmyproject/adapters/grpcserverb\x06proto3"

var (
	file_adapters_grpcserver_task_manager_proto_rawDescOnce sync.Once
	file_adapters_grpcserver_task_manager_proto_rawDescData []byte
)

func file_adapters_grpcserver_task_manager_proto_rawDescGZIP() []byte {
	file_adapters_grpcserver_task_manager_proto_rawDescOnce.Do(func() {
		file_adapters_grpcserver_task_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_adapters_grpcserver_task_manager_proto_rawDesc), len(file_adapters_grpcserver_task_manager_proto_rawDesc)))
	})
	return file_adapters_grpcserver_task_manager_proto_rawDescData
}

var file_adapters_grpcserver_task_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_adapters_grpcserver_task_manager_proto_goTypes = []any{
	(*RegisterRequest)(nil),    // 0: grpcserver.RegisterRequest
	(*RegisterReply)(nil),      // 1: grpcserver.RegisterReply
	(*LoginRequest)(nil),       // 2: grpcserver.LoginRequest
	(*LoginReply)(nil),         // 3: grpcserver.LoginReply
	(*CreateTaskRequest)(nil),  // 4: grpcserver.CreateTaskRequest
	(*CreateTaskReply)(nil),    // 5: grpcserver.CreateTaskReply
	(*GetTasksRequest)(nil),    // 6: grpcserver.GetTasksRequest
	(*GetTasksReply)(nil),      // 7: grpcserver.GetTasksReply
	(*GetTasksReply_Task)(nil), // 8: grpcserver.GetTasksReply.Task
}
var file_adapters_grpcserver_task_manager_proto_depIdxs = []int32{
	8, // 0: grpcserver.GetTasksReply.tasks:type_name -> grpcserver.GetTasksReply.Task
	0, // 1: grpcserver.TaskManager.Register:input_type -> grpcserver.RegisterRequest
	2, // 2: grpcserver.TaskManager.Login:input_type -> grpcserver.LoginRequest
	4, // 3: grpcserver.TaskManager.CreateTask:input_type -> grpcserver.CreateTaskRequest
	6, // 4: grpcserver.TaskManager.GetTasks:input_type -> grpcserver.GetTasksRequest
	1, // 5: grpcserver.TaskManager.Register:output_type -> grpcserver.RegisterReply
	3, // 6: grpcserver.TaskManager.Login:output_type -> grpcserver.LoginReply
	5, // 7: grpcserver.TaskManager.CreateTask:output_type -> grpcserver.CreateTaskReply
	7, // 8: grpcserver.TaskManager.GetTasks:output_type -> grpcserver.GetTasksReply
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_adapters_grpcserver_task_manager_proto_init() }
func file_adapters_grpcserver_task_manager_proto_init() {
	if File_adapters_grpcserver_task_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_adapters_grpcserver_task_manager_proto_rawDesc), len(file_adapters_grpcserver_task_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_adapters_grpcserver_task_manager_proto_goTypes,
		DependencyIndexes: file_adapters_grpcserver_task_manager_proto_depIdxs,
		MessageInfos:      file_adapters_grpcserver_task_manager_proto_msgTypes,
	}.Build()
	File_adapters_grpcserver_task_manager_proto = out.File
	file_adapters_grpcserver_task_manager_proto_goTypes = nil
	file_adapters_grpcserver_task_manager_proto_depIdxs = nil
}
